"""empty message

Revision ID: 3e1f0ce969a4
Revises: e0372a1bf8e0
Create Date: 2019-08-31 21:17:05.497656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1f0ce969a4'
down_revision = 'e0372a1bf8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replys', sa.Column('state', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replys', 'state')
    # ### end Alembic commands ###
