"""empty message

Revision ID: e0372a1bf8e0
Revises: 7d364b7dc594
Create Date: 2019-08-31 21:15:41.776005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0372a1bf8e0'
down_revision = '7d364b7dc594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=False),
    sa.Column('replyer', sa.String(length=64), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replys_time_stamp'), 'replys', ['time_stamp'], unique=False)
    op.add_column('attentions', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.drop_constraint('attentions_ibfk_1', 'attentions', type_='foreignkey')
    op.create_foreign_key(None, 'attentions', 'users', ['receiver_id'], ['id'])
    op.drop_column('attentions', 'reciever_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attentions', sa.Column('reciever_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attentions', type_='foreignkey')
    op.create_foreign_key('attentions_ibfk_1', 'attentions', 'users', ['reciever_id'], ['id'])
    op.drop_column('attentions', 'receiver_id')
    op.drop_index(op.f('ix_replys_time_stamp'), table_name='replys')
    op.drop_table('replys')
    # ### end Alembic commands ###
